import { logger } from "@/utils/log-utility";
import { spineOptionsSchema } from "@/ink/spine-options-schema.generated";
import { Assets, canvas } from "@drincs/pixi-vn";
import { HashtagCommands } from "@drincs/pixi-vn-ink";
import {
    ENTRANCE_TRANSITION_TYPES,
    type EntranceTransitionType,
    entranceTransitionKeySchemas,
    executeEntranceTransition,
} from "@drincs/pixi-vn-json/actions";
import type { SpineOptions } from "@drincs/pixi-vn-spine";
import { Spine } from "@drincs/pixi-vn-spine";
import { z } from "zod";

/**
 * Options for {@link createSpineHandler}.
 */
export interface SpineHandlerOptions {
    /**
     * Known asset aliases — e.g. `assetAliasIds` from the file generated by `vitePluginPixivn`'s
     * `assetsManifest` option. When provided, the `<alias>` position of `# show spine` does a
     * runtime membership check instead of accepting any string.
     */
    assetAliasIds?: readonly string[];
}

function idSchema(
    ids: readonly string[] | undefined,
): z.ZodString | z.ZodEnum<Record<string, string>> {
    if (ids && ids.length > 0) {
        return z.enum(Object.fromEntries(ids.map((id) => [id, id])));
    }
    return z.string();
}

/**
 * {@link spineOptionsSchema} accurately marks `skeleton` as required — it's a real, required
 * `SpineOptions` field — but `# show spine <alias> ...` never spells it out as one of the
 * command's own `<key> <value>` props: it's always the `<alias>` token itself. Dropping it here
 * keeps the static `keySchemas` validation of the props section from flagging every `# show spine`
 * command as missing a "skeleton" prop.
 */
function buildShowSpinePropsSchema(): object {
    const schema = spineOptionsSchema as {
        properties?: Record<string, object>;
        required?: string[];
        [key: string]: unknown;
    };
    const { skeleton: _skeleton, ...properties } = schema.properties ?? {};
    return {
        ...schema,
        properties,
        required: (schema.required ?? []).filter((key) => key !== "skeleton"),
    };
}

const showSpinePropsSchema = buildShowSpinePropsSchema();

/**
 * Splits the tail (everything after `<alias>`) of a `# show spine` command into its free-form
 * construction props and an optional entrance transition.
 */
export function parseShowSpineTail(tail: string[]): {
    propsList: string[];
    transitionType?: EntranceTransitionType;
    transitionPropsList: string[];
} {
    let propsList = tail;
    let transitionType: EntranceTransitionType | undefined;
    let transitionPropsList: string[] = [];
    const withIndex = propsList.indexOf("with");
    if (withIndex !== -1 && propsList.length > withIndex + 1) {
        const rawType = propsList[withIndex + 1];
        if ((ENTRANCE_TRANSITION_TYPES as readonly string[]).includes(rawType)) {
            transitionType = rawType as EntranceTransitionType;
            transitionPropsList = propsList.slice(withIndex + 2);
        }
        propsList = propsList.slice(0, withIndex);
    }

    return { propsList, transitionType, transitionPropsList };
}

/**
 * Registers the `# show spine` Ink hashtag command, letting Ink scripts show a {@link Spine}
 * canvas element the same way `@drincs/pixi-vn-ink`'s built-in `# show image` shows an
 * `ImageSprite`: the alias also doubles as the skeleton asset alias, free-form `<key> <value>`
 * construction props are forwarded to {@link SpineOptions} (an `atlas` prop is required, since
 * unlike an image's single URL, a Spine skeleton always needs a matching atlas alias), and an
 * optional entrance transition can run the element in.
 *
 * Call this once, near the start of your app (alongside e.g. `addBaseHashtagCommands`), before any
 * Ink content is parsed.
 *
 * @example
 * ```ink
 * # show spine heroSkeleton atlas heroAtlas xAlign 0.5 yAlign 1 with dissolve duration 1
 * ```
 * @param options Optional configuration for known asset-alias ids.
 */
export function createSpineHandler(options: SpineHandlerOptions = {}): void {
    async function runShowSpine(
        alias: string,
        tail: string[],
        convertListStringToObj: (listParm: string[]) => object,
    ): Promise<boolean> {
        const { propsList, transitionType, transitionPropsList } = parseShowSpineTail(tail);

        let props: Record<string, unknown> = {};
        if (propsList.length > 0) {
            try {
                props = convertListStringToObj(propsList) as Record<string, unknown>;
            } catch (e) {
                logger.error(`Failed to parse props for "show spine ${alias}"`, e);
                return true;
            }
        }
        const { atlas, ...rest } = props;
        if (typeof atlas !== "string") {
            logger.error(
                `"show spine ${alias}" requires an "atlas" prop with the atlas asset alias, e.g. "atlas myAtlasAlias"`,
            );
            return true;
        }

        await Assets.load([alias, atlas]);
        const spine = new Spine({
            ...(rest as Partial<SpineOptions>),
            skeleton: alias,
            atlas,
        });

        if (transitionType) {
            let transitionProps: object | undefined;
            if (transitionPropsList.length > 0) {
                try {
                    transitionProps = convertListStringToObj(transitionPropsList);
                } catch (e) {
                    logger.error(`Failed to parse transition props for "show spine ${alias}"`, e);
                }
            }
            await executeEntranceTransition(alias, spine, transitionType, transitionProps);
        } else {
            canvas.add(alias, spine);
        }
        return true;
    }

    HashtagCommands.add(
        (list, _props, convertListStringToObj) =>
            runShowSpine(list[2], list.slice(3), convertListStringToObj),
        {
            name: "Show spine",
            description: `Shows a Spine canvas element with optional key/value construction properties (forwarded to \`SpineOptions\`) and an entrance transition. The \`skeleton\` and \`atlas\` fields are both required: \`<alias>\` doubles as the \`skeleton\` asset alias, and an \`atlas\` prop (asset alias) must be provided among the key/value properties, e.g. "atlas myAtlasAlias".

\`\`\`ink
# show spine <alias> [<key> <value> …] [with dissolve|fade|movein|moveout|zoomin|zoomout|pushin|pushout [<key> <value> …]]
\`\`\``,
            validation: z
                .tuple([z.literal("show"), z.literal("spine"), idSchema(options.assetAliasIds)])
                .rest(z.string()),
            keySchemas: {
                with: {},
                ...entranceTransitionKeySchemas,
                3: showSpinePropsSchema,
            },
        },
    );
}
