import { logger } from "@/utils/log-utility";
import { spineOptionsSchema } from "@/ink/spine-options-schema.generated";
import { Assets, canvas } from "@drincs/pixi-vn";
import {
    moveOut,
    pushOut,
    removeWithDissolve,
    removeWithFade,
    zoomOut,
} from "@drincs/pixi-vn/canvas";
import { HashtagCommands } from "@drincs/pixi-vn-ink";
import {
    containerMemorySchema,
    ENTRANCE_TRANSITION_TYPES,
    type EntranceTransitionType,
    entranceTransitionKeySchemas,
    executeEntranceTransition,
} from "@drincs/pixi-vn-json/actions";
import type { SpineOptions } from "@drincs/pixi-vn-spine";
import { Spine } from "@drincs/pixi-vn-spine";
import { z } from "zod";

/**
 * The transition types used to remove a canvas element **out** (as opposed to
 * `dissolve`/`fade`/`movein`/`zoomin`/`pushin`, used only to bring one in). Mirrors
 * `@drincs/pixi-vn-json/actions`' own `ENTRANCE_TRANSITION_TYPES`, but for `# remove spine`.
 */
const EXIT_TRANSITION_TYPES = ["dissolve", "fade", "moveout", "zoomout", "pushout"] as const;
type ExitTransitionType = (typeof EXIT_TRANSITION_TYPES)[number];

/**
 * Runs an exit transition on a canvas element, mirroring `@drincs/pixi-vn-json/actions`'
 * `executeEntranceTransition` but for removal — `@drincs/pixi-vn-json` doesn't (yet) expose an
 * equivalent helper for the exit direction, so this dispatches straight to `@drincs/pixi-vn/canvas`.
 */
function executeExitTransition(
    alias: string,
    transitionType: ExitTransitionType,
    props?: object,
): string[] | undefined {
    switch (transitionType) {
        case "dissolve":
            return removeWithDissolve(alias, props);
        case "fade":
            return removeWithFade(alias, props);
        case "moveout":
            return moveOut(alias, props);
        case "zoomout":
            return zoomOut(alias, props);
        case "pushout":
            return pushOut(alias, props);
    }
}

/**
 * Options for {@link createSpineHandler}.
 */
export interface SpineHandlerOptions {
    /**
     * Known asset aliases — e.g. `assetAliasIds` from the file generated by `vitePluginPixivn`'s
     * `assetsManifest` option. When provided, the `<alias>` position of `# show spine` does a
     * runtime membership check instead of accepting any string.
     */
    assetAliasIds?: readonly string[];
}

function idSchema(
    ids: readonly string[] | undefined,
): z.ZodString | z.ZodEnum<Record<string, string>> {
    if (ids && ids.length > 0) {
        return z.enum(Object.fromEntries(ids.map((id) => [id, id])));
    }
    return z.string();
}

/**
 * {@link spineOptionsSchema} accurately marks `skeleton` as required — it's a real, required
 * `SpineOptions` field — but `# show spine <alias> ...` never spells it out as one of the
 * command's own `<key> <value>` props: it's always the `<alias>` token itself. Dropping it here
 * keeps the static `keySchemas` validation of the props section from flagging every `# show spine`
 * command as missing a "skeleton" prop.
 */
function buildShowSpinePropsSchema(): object {
    const schema = spineOptionsSchema as {
        properties?: Record<string, object>;
        required?: string[];
        [key: string]: unknown;
    };
    const { skeleton: _skeleton, ...properties } = schema.properties ?? {};
    return {
        ...schema,
        properties,
        required: (schema.required ?? []).filter((key) => key !== "skeleton"),
    };
}

const showSpinePropsSchema = buildShowSpinePropsSchema();

/** Mirrors {@link Spine.addAnimation}'s own inline options type. */
const addAnimationOptionsSchema = {
    type: "object",
    properties: {
        loop: { type: "boolean" },
        delay: { type: "number" },
        trackIndex: { type: "number" },
        completeOnContinue: { type: "boolean" },
    },
    additionalProperties: false,
};

/** Mirrors {@link Spine.setAnimation}'s own inline options type — `trackIndex` is required. */
const setAnimationOptionsSchema = {
    type: "object",
    properties: {
        trackIndex: { type: "number" },
        loop: { type: "boolean" },
        completeOnContinue: { type: "boolean" },
    },
    required: ["trackIndex"],
    additionalProperties: false,
};

type AddAnimationOptions = Parameters<Spine["addAnimation"]>[1];
type SetAnimationOptions = Parameters<Spine["setAnimation"]>[1];

/**
 * Splits the tail (everything after `<alias>`) of a `# show spine` command into its free-form
 * construction props and an optional entrance transition.
 */
export function parseShowSpineTail(tail: string[]): {
    propsList: string[];
    transitionType?: EntranceTransitionType;
    transitionPropsList: string[];
} {
    let propsList = tail;
    let transitionType: EntranceTransitionType | undefined;
    let transitionPropsList: string[] = [];
    const withIndex = propsList.indexOf("with");
    if (withIndex !== -1 && propsList.length > withIndex + 1) {
        const rawType = propsList[withIndex + 1];
        if ((ENTRANCE_TRANSITION_TYPES as readonly string[]).includes(rawType)) {
            transitionType = rawType as EntranceTransitionType;
            transitionPropsList = propsList.slice(withIndex + 2);
        }
        propsList = propsList.slice(0, withIndex);
    }

    return { propsList, transitionType, transitionPropsList };
}

/**
 * Registers the `# show spine` Ink hashtag command, letting Ink scripts show a {@link Spine}
 * canvas element the same way `@drincs/pixi-vn-ink`'s built-in `# show image` shows an
 * `ImageSprite`: the alias also doubles as the skeleton asset alias, free-form `<key> <value>`
 * construction props are forwarded to {@link SpineOptions} (an `atlas` prop is required, since
 * unlike an image's single URL, a Spine skeleton always needs a matching atlas alias), and an
 * optional entrance transition can run the element in.
 *
 * Call this once, near the start of your app (alongside e.g. `addBaseHashtagCommands`), before any
 * Ink content is parsed.
 *
 * @example
 * ```ink
 * # show spine heroSkeleton atlas heroAtlas xAlign 0.5 yAlign 1 with dissolve duration 1
 * ```
 * @param options Optional configuration for known asset-alias ids.
 */
export function createSpineHandler(options: SpineHandlerOptions = {}): void {
    async function runShowSpine(
        alias: string,
        tail: string[],
        convertListStringToObj: (listParm: string[]) => object,
    ): Promise<boolean> {
        const { propsList, transitionType, transitionPropsList } = parseShowSpineTail(tail);

        let props: Record<string, unknown> = {};
        if (propsList.length > 0) {
            try {
                props = convertListStringToObj(propsList) as Record<string, unknown>;
            } catch (e) {
                logger.error(`Failed to parse props for "show spine ${alias}"`, e);
                return true;
            }
        }
        const { atlas, ...rest } = props;
        if (typeof atlas !== "string") {
            logger.error(
                `"show spine ${alias}" requires an "atlas" prop with the atlas asset alias, e.g. "atlas myAtlasAlias"`,
            );
            return true;
        }

        await Assets.load([alias, atlas]);
        const spine = new Spine({
            ...(rest as Partial<SpineOptions>),
            skeleton: alias,
            atlas,
        });

        if (transitionType) {
            let transitionProps: object | undefined;
            if (transitionPropsList.length > 0) {
                try {
                    transitionProps = convertListStringToObj(transitionPropsList);
                } catch (e) {
                    logger.error(`Failed to parse transition props for "show spine ${alias}"`, e);
                }
            }
            await executeEntranceTransition(alias, spine, transitionType, transitionProps);
        } else {
            canvas.add(alias, spine);
        }
        return true;
    }

    HashtagCommands.add(
        (list, _props, convertListStringToObj) =>
            runShowSpine(list[2], list.slice(3), convertListStringToObj),
        {
            name: "Show spine",
            description: `Shows a Spine canvas element with optional key/value construction properties (forwarded to \`SpineOptions\`) and an entrance transition. The \`skeleton\` and \`atlas\` fields are both required: \`<alias>\` doubles as the \`skeleton\` asset alias, and an \`atlas\` prop (asset alias) must be provided among the key/value properties, e.g. "atlas myAtlasAlias".

\`\`\`ink
# show spine <alias> [<key> <value> …] [with dissolve|fade|movein|moveout|zoomin|zoomout|pushin|pushout [<key> <value> …]]
\`\`\``,
            validation: z
                .tuple([z.literal("show"), z.literal("spine"), idSchema(options.assetAliasIds)])
                .rest(z.string()),
            keySchemas: {
                with: {},
                ...entranceTransitionKeySchemas,
                3: showSpinePropsSchema,
            },
        },
    );

    function runEditSpine(
        alias: string,
        tail: string[],
        convertListStringToObj: (listParm: string[]) => object,
    ): boolean {
        const spine = canvas.find<Spine>(alias);
        if (!spine) {
            logger.error(`"edit spine ${alias}": no Spine canvas element found with this alias`);
            return true;
        }
        if (tail.length === 0) {
            return true;
        }
        try {
            const props = convertListStringToObj(tail);
            Object.assign(spine, props);
        } catch (e) {
            logger.error(`Failed to parse props for "edit spine ${alias}"`, e);
        }
        return true;
    }

    HashtagCommands.add(
        (list, _props, convertListStringToObj) =>
            runEditSpine(list[2], list.slice(3), convertListStringToObj),
        {
            name: "Edit spine",
            description: `Edits the properties of a Spine canvas element identified by its alias, using key/value properties (e.g. alpha, tint, x, y, visible, xAlign, ...).

\`\`\`ink
# edit spine <alias> [<key> <value> …]
\`\`\``,
            validation: z
                .tuple([z.literal("edit"), z.literal("spine"), z.string()])
                .rest(z.string()),
            keySchemas: {
                3: containerMemorySchema,
            },
        },
    );

    function runRemoveSpine(
        alias: string,
        tail: string[],
        convertListStringToObj: (listParm: string[]) => object,
    ): boolean {
        const spine = canvas.find<Spine>(alias);
        if (!spine) {
            logger.error(`"remove spine ${alias}": no Spine canvas element found with this alias`);
            return true;
        }

        let transitionType: ExitTransitionType | undefined;
        let transitionPropsList: string[] = [];
        const withIndex = tail.indexOf("with");
        if (withIndex !== -1 && tail.length > withIndex + 1) {
            const rawType = tail[withIndex + 1];
            if ((EXIT_TRANSITION_TYPES as readonly string[]).includes(rawType)) {
                transitionType = rawType as ExitTransitionType;
                transitionPropsList = tail.slice(withIndex + 2);
            }
        }

        if (transitionType) {
            let transitionProps: object | undefined;
            if (transitionPropsList.length > 0) {
                try {
                    transitionProps = convertListStringToObj(transitionPropsList);
                } catch (e) {
                    logger.error(`Failed to parse transition props for "remove spine ${alias}"`, e);
                }
            }
            executeExitTransition(alias, transitionType, transitionProps);
        } else {
            canvas.remove(alias);
        }
        return true;
    }

    HashtagCommands.add(
        (list, _props, convertListStringToObj) =>
            runRemoveSpine(list[2], list.slice(3), convertListStringToObj),
        {
            name: "Remove spine",
            description: `Removes a Spine canvas element with an optional exit transition.

\`\`\`ink
# remove spine <alias> [with dissolve|fade|movein|moveout|zoomin|zoomout|pushin|pushout [<key> <value> …]]
\`\`\``,
            validation: z
                .tuple([z.literal("remove"), z.literal("spine"), z.string()])
                .rest(z.string()),
            keySchemas: {
                with: {},
                dissolve: entranceTransitionKeySchemas.dissolve,
                fade: entranceTransitionKeySchemas.fade,
                moveout: entranceTransitionKeySchemas.movein,
                zoomout: entranceTransitionKeySchemas.zoomin,
                pushout: entranceTransitionKeySchemas.pushin,
            },
        },
    );

    function findSpineOrLogError(commandLabel: string, alias: string): Spine | undefined {
        const spine = canvas.find<Spine>(alias);
        if (!spine) {
            logger.error(`"${commandLabel}": no Spine canvas element found with alias "${alias}"`);
        }
        return spine;
    }

    HashtagCommands.add(
        (list) => {
            const alias = list[2];
            const skinName = list[3];
            const spine = findSpineOrLogError(`set skin ${alias} ${skinName}`, alias);
            spine?.setSkin(skinName);
            return true;
        },
        {
            name: "Set skin",
            description: `Sets the active skin on a Spine canvas element identified by its alias.

\`\`\`ink
# set skin <alias> <skinName>
\`\`\``,
            validation: z.tuple([z.literal("set"), z.literal("skin"), z.string(), z.string()]),
        },
    );

    HashtagCommands.add(
        (list) => {
            const alias = list[2];
            const trackIndexRaw = list[3];
            const spine = findSpineOrLogError(`clear track ${alias} ${trackIndexRaw}`, alias);
            if (!spine) {
                return true;
            }
            const trackIndex = Number(trackIndexRaw);
            if (!Number.isFinite(trackIndex)) {
                logger.error(`"clear track ${alias} ${trackIndexRaw}": invalid track index`);
                return true;
            }
            spine.clearTrack(trackIndex);
            return true;
        },
        {
            name: "Clear track",
            description: `Clears a single animation track on a Spine canvas element identified by its alias, stopping any running sequence on it and leaving the skeleton in its current pose.

\`\`\`ink
# clear track <alias> <trackIndex>
\`\`\``,
            validation: z.tuple([z.literal("clear"), z.literal("track"), z.string(), z.string()]),
        },
    );

    HashtagCommands.add(
        (list, _props, convertListStringToObj) => {
            const alias = list[2];
            const animationName = list[3];
            const spine = findSpineOrLogError(`add animation ${alias} ${animationName}`, alias);
            if (!spine) {
                return true;
            }
            const tail = list.slice(4);
            let options: AddAnimationOptions = {};
            if (tail.length > 0) {
                try {
                    options = convertListStringToObj(tail) as AddAnimationOptions;
                } catch (e) {
                    logger.error(
                        `Failed to parse options for "add animation ${alias} ${animationName}"`,
                        e,
                    );
                    return true;
                }
            }
            spine.addAnimation(animationName, options);
            return true;
        },
        {
            name: "Add animation",
            description: `Queues an animation to play after the current one on a track, on a Spine canvas element identified by its alias. Optional key/value properties: loop, delay, trackIndex, completeOnContinue.

\`\`\`ink
# add animation <alias> <animationName> [<key> <value> …]
\`\`\``,
            validation: z
                .tuple([z.literal("add"), z.literal("animation"), z.string(), z.string()])
                .rest(z.string()),
            keySchemas: {
                4: addAnimationOptionsSchema,
            },
        },
    );

    HashtagCommands.add(
        (list, _props, convertListStringToObj) => {
            const alias = list[2];
            const animationName = list[3];
            const spine = findSpineOrLogError(`set animation ${alias} ${animationName}`, alias);
            if (!spine) {
                return true;
            }
            let options: Record<string, unknown>;
            try {
                options = convertListStringToObj(list.slice(4)) as Record<string, unknown>;
            } catch (e) {
                logger.error(
                    `Failed to parse options for "set animation ${alias} ${animationName}"`,
                    e,
                );
                return true;
            }
            if (typeof options.trackIndex !== "number") {
                logger.error(
                    `"set animation ${alias} ${animationName}" requires a numeric "trackIndex" prop, e.g. "trackIndex 0"`,
                );
                return true;
            }
            spine.setAnimation(animationName, options as SetAnimationOptions);
            return true;
        },
        {
            name: "Set animation",
            description: `Sets the current animation on a track, replacing whatever is currently playing on it, on a Spine canvas element identified by its alias. Requires a numeric "trackIndex" prop; optional: loop, completeOnContinue.

\`\`\`ink
# set animation <alias> <animationName> <key> <value> [<key> <value> …]
# set animation hero walk trackIndex 0 loop true
\`\`\``,
            validation: z
                .tuple([z.literal("set"), z.literal("animation"), z.string(), z.string()])
                .rest(z.string()),
            keySchemas: {
                4: setAnimationOptionsSchema,
            },
        },
    );
}
