import { SkeletonData as CoreSkeletonData, SpineOptions as CoreSpineOptions } from "@drincs/pixi-vn-spine/core";
export default interface SpineOptions
    extends Omit<
        CoreSpineOptions,
        | "skeletonData"
        | "cacheAsTexture"
        | "boundsArea"
        | "boundsProvider"
        | "cullArea"
        | "darkTint"
        | "hitArea"
        | "mask"
        | "onclick"
        | "onglobalmousemove"
        | "onglobalpointermove"
        | "onmousemove"
        | "onpointermove"
        | "onglobaltouchmove"
        | "ontouchmove"
        | "onmousedown"
        | "onmouseenter"
        | "onmouseleave"
        | "onmouseout"
        | "onmouseover"
        | "onmouseup"
        | "onmouseupoutside"
        | "onpointercancel"
        | "onpointerenter"
        | "onpointerdown"
        | "onpointerleave"
        | "onpointerout"
        | "onpointerover"
        | "onpointertap"
        | "onpointerup"
        | "onrightdown"
        | "onrightup"
        | "ontouchcancel"
        | "onRender"
        | "onpointerupoutside"
        | "onrightclick"
        | "onrightupoutside"
        | "ontap"
        | "ontouchendoutside"
        | "ontouchend"
        | "ontouchstart"
        | "onwheel"
        | "children"
        | "filters"
        | "parent"
        | "setMask"
    > {
    skeletonData?: SkeletonData;
}
export interface SkeletonData
    extends Partial<
        Omit<
            CoreSkeletonData,
            | "findAnimation"
            | "findBone"
            | "findEvent"
            | "findIkConstraint"
            | "findPathConstraint"
            | "findPhysicsConstraint"
            | "findSkin"
            | "findSlot"
            | "findTransformConstraint"
            | "animations"
            | "bones"
            | "defaultSkin"
        >
    > {}
